sesamyab/wordpress-sesamy

- package.json
> chore: remove v in format

- src/public/class-sesamy-content-container.php
> fix: quotes

- Dockerfile
- src/admin/class-sesamy-settings-admin.php
- src/public/sesamy-global-functions.php
Added an encode lock mode that base64-encodes the locked content before writing it to page.
> feat: add support for encode mode

- src/admin/class-sesamy-admin-view.php
- src/admin/class-sesamy-post-editor.php
- src/admin/class-sesamy-settings-admin.php
- src/admin/gutenberg/sesamy-post-editor/src/sesamyPostEditor.js
- src/includes/class-sesamy-passes.php
- src/includes/class-sesamy-post-properties.php
- src/includes/class-sesamy-settings.php
- src/public/class-sesamy-content-container.php
- src/public/class-sesamy-meta.php
- src/public/sesamy-global-functions.php
> Added currency option globally and removed from post and category

- src/public/class-sesamy-meta.php
> Added category and tags metatags

- src/admin/class-sesamy-admin-view.php
- src/admin/gutenberg/sesamy-post-editor/src/sesamyPostEditor.js
- src/includes/class-sesamy-post-properties.php
- src/includes/class-sesamy.php
- src/public/sesamy-global-functions.php
Fixes 3 issue and add access level option
> Fixing 3 small issue 19122023

- src/README.txt
- src/admin/class-sesamy-post-editor.php
- src/includes/class-sesamy-api-endpoint.php
- src/includes/class-sesamy-utils.php
- src/public/sesamy-global-functions.php
- src/sesamy.php
Fixed get_site_url and wp_kses_post issue for API endpoint
> Fixed API endpoint issue

- src/README.txt
- src/admin/class-sesamy-admin-view.php
- src/admin/class-sesamy-settings-admin.php
- src/admin/gutenberg/sesamy-post-editor/src/sesamyPostEditor.js
- src/includes/class-sesamy-post-properties.php
- src/includes/class-sesamy-tags.php
- src/includes/class-sesamy.php
- src/public/sesamy-global-functions.php
- src/sesamy.php
- Remove "jstensved" name from Contributors
- Change URL "https://sesamy.com"
- Added Sesamy Attribute Support
> Added Sesamy Attribute Support

- src/README.txt
- src/admin/class-sesamy-admin-view.php
- src/admin/gutenberg/sesamy-post-editor/src/sesamyPostEditor.js
- src/sesamy.php
Fixed Sesamy Attribute count issue
> Fixed Sesamy Attribute count issue

- src/includes/class-sesamy-settings.php
- src/public/sesamy-global-functions.php
Remove unnecessary scripts and tags
> Remove unnecessary scripts and tags

- src/README.txt
- src/sesamy.php
> Add version change

- src/README.txt
- src/sesamy.php
> Fixed version conflict issue

- src/sesamy.php
> Downgrade version number

- src/includes/class-sesamy-api-endpoint.php
- src/public/sesamy-global-functions.php
This issues was reported by Whynow, if the lock mode is SignedURL and the post is not locked (paywall not enabled) the content is empty.
This fix will render the content of the post, further investigation into the web component is needed.
> fix: show content if signed url not locked

- src/public/class-sesamy-content-container.php
Hide the paywall if the access level of the post is `public`
> fix: hide paywall if public

- src/README.txt
- src/public/class-sesamy-content-container.php
- src/public/sesamy-global-functions.php
- src/sesamy.php
- src/version.php
Always display the locked content if the lock mode is "None"
> fix: treat none lock mode as public

- src/README.txt
- src/admin/gutenberg/sesamy-post-editor/src/sesamyPostEditor.js
- src/includes/class-sesamy-post-properties.php
- src/public/class-sesamy-content-container.php
- src/public/class-sesamy-shortcodes.php
- src/public/sesamy-global-functions.php
- src/sesamy.php
- src/version.php
- Enable/disable paywall wizard form the edit post screen.
- Enable/disable login button.
> feat: paywall wizard

- src/admin/class-sesamy-admin-view.php
- src/admin/class-sesamy-settings-admin.php
- src/includes/class-sesamy-currencies.php
- src/includes/class-sesamy-post-properties.php
- src/includes/class-sesamy-settings.php
- src/public/class-sesamy-content-container.php
- src/public/class-sesamy-meta.php
- src/public/sesamy-global-functions.php
- Fixed typo: sesamy_gloabl_currency -> sesamy_global_currency
- Used hardcoded currencies instead of the ones from market.json file from the assets site (outdated, need to find a better way of find the currencies).
> feat: gbp currency

- src/README.txt
- src/public/class-sesamy-content-container.php
- src/sesamy.php
- src/version.php
- Sanitize description in paywall wizard.
- Shadow border added to paywall wizard.
> fix: paywall sanitize json

- src/admin/class-sesamy-settings-admin.php
- src/admin/gutenberg/sesamy-post-editor/src/sesamyPostEditor.js
- src/includes/class-sesamy-post-properties.php
- src/includes/class-sesamy-settings.php
- src/public/class-sesamy-content-container.php
- src/public/sesamy-global-functions.php
This changes so that the paywall is configured via the sesamy portal instead of directly in wordpress.
> fix: change to use sesamy paywall wizard config

- README.md
- src/README.txt
- src/sesamy.php
- src/version.php
Bump the version to publish to the wordpress store
> chore: release 3.0.0
